# Generated by Django 5.1.6 on 2025-03-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='modelo_string_2_50',
            new_name='modelo',
        ),
    ]
