# Generated by Django 5.0 on 2025-03-25 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_remove_passport_id_passport_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='person',
        ),
        migrations.AddField(
            model_name='passport',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='aula.person', verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
