# Generated by Django 5.0 on 2025-03-25 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_remove_passport_person_passport_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='...', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(help_text='#####@mail.com', max_length=254, verbose_name='Email')),
                ('cpf', models.CharField(help_text='Valid CPF...', max_length=11, verbose_name='CPF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='...', max_length=100, verbose_name='Number')),
                ('pub_date', models.DateField(verbose_name='Publish Date')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.reporter', verbose_name='Reporter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
