# Generated by Django 5.0 on 2025-03-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_reporter_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='...', max_length=100, verbose_name='Title'),
        ),
    ]
