# Generated by Django 5.0 on 2025-03-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='...', max_length=100, verbose_name='Name')),
                ('edition', models.DateField(verbose_name='Edition')),
                ('article', models.ManyToManyField(to='aula.article', verbose_name='Articles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
