# Generated by Django 5.1.6 on 2025-03-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0007_alter_magazine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='name',
            field=models.CharField(help_text='...', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(help_text='...', max_length=15, verbose_name='Number'),
        ),
    ]
